client_config_backend: settings
client_config:
  client_id: 737282666298-sjsr7ksevgp4jf5j0bj145ct2oul18ou.apps.googleusercontent.com
  client_secret: boGTAu0qPuDbVLerP6hptnic

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive