# Generated by Django 3.2.5 on 2021-07-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFileName', models.CharField(default=None, max_length=200, null=True)),
                ('videoTimeline', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('groupImage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_api.groupimage')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedThumbnails', models.TextField(blank=True, null=True)),
                ('groupImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.groupimage')),
            ],
        ),
    ]
