# Generated by Django 3.2.5 on 2021-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupimage',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
