# Generated by Django 3.2.5 on 2021-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_groupimage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimage',
            name='importedVideos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupimage',
            name='projectName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
