# Generated by Django 3.2.5 on 2021-07-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_groupimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtimeline',
            name='videoFileName',
        ),
        migrations.AddField(
            model_name='generatedtimeline',
            name='groupImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.groupimage'),
        ),
    ]
